name: Restream YouTube Live to RTMP

on:
  push:
    branches:
      - main  # Triggers on pushes to the 'main' branch
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  restream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest version of Python 3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Run the restream script
        env:
          RTMP_URL: ${{ secrets.RTMP_URL }}  # Using GitHub secret for RTMP URL
        run: |
          python yt.py
