name: Live Stream Deployment (Restream Only)

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: restream-deploy
  cancel-in-progress: false

jobs:
  deploy-restream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install FFmpeg (Full Version)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libavcodec-extra

      - name: Debug Secrets
        run: |
          echo "Checking if RTMP_URL is set..."
          if [ -z "${{ secrets.RTMP_URL }}" ]; then
            echo "❌ ERROR: RTMP_URL is NOT set!"
            exit 1
          else
            echo "✅ RTMP_URL is set."
          fi

      - name: Pre-allocate Resources (buffer tuning)
        run: |
          ulimit -n 8192
          sysctl -w net.core.rmem_max=16777216
          sysctl -w net.core.wmem_max=16777216
          sysctl -w net.ipv4.tcp_rmem='4096 87380 16777216'
          sysctl -w net.ipv4.tcp_wmem='4096 65536 16777216'

      - name: Delay Before Streaming
        run: sleep 10

      - name: Run live stream script (restream.py)
        env:
          RTMP_URL: ${{ secrets.RTMP_URL }}
        run: |
          echo "🚀 Starting restream..."
          python3 restream.py
